"""
sh_hue — Philips Hue controller skill.

Wraps the `phue` library so `core.smart_home_router` can dispatch on/off,
brightness and color commands to Hue bulbs without going through Alexa.

Bridge IP + username are stored in `data/sh_hue_config.json`:
    {"bridge_ip": "192.168.1.10", "username": "...generated by phue..."}

If the bridge IP is unknown the skill tries the Hue cloud discovery
endpoint at meethue.com — but only if `requests` is available and the
file doesn't already exist. Username is created via the press-the-button
flow on first connect; the user has to physically press the Hue bridge
button within 30 seconds of the first `phue.Bridge(...)` call.

All public functions (`is_available`, `list_devices`, `get_state`,
`set_state`) gracefully degrade if `phue` isn't installed or the bridge
isn't reachable — they return informative dicts rather than raising.

Uniform set_state kwargs (a subset of these will be honored depending
on the bulb's capabilities):
    on:         bool
    brightness: 0..100      (percent, mapped to phue's 0..254)
    color:      (r, g, b)   (255-scale, converted to xy)
    color_name: str         (preserved in return value for logging)
    color_temperature: int  (kelvin, mapped to phue's mireds 153..500)
"""
from __future__ import annotations

import ipaddress
import json
import os
import socket
import threading
import time
from typing import Any


_PROJECT_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
# STAGING ISOLATION (2026-07-21): resolve through core.paths so a
# JARVIS_STAGING process writes data_staging/ instead of the live data/.
# A private join here is how a staging-isolated action sweep overwrote the
# LIVE smart-home catalog while the settings md5 tripwire stayed green.
try:
    from core.paths import data_dir as _jarvis_data_dir
    _DATA_DIR = _jarvis_data_dir()
except Exception:   # pragma: no cover - core.paths is in-tree
    _DATA_DIR = os.path.join(_PROJECT_DIR, "data")
_CONFIG_PATH = os.path.join(_DATA_DIR, "sh_hue_config.json")

_lock = threading.Lock()
_bridge_cache: dict[str, Any] = {"bridge": None, "lights_by_name": {},
                                  "fetched_at": 0.0}
_CACHE_TTL_SECS = 30.0

# Connect can block up to 30 s waiting for the user to press the Hue bridge
# button.  In a voice loop we cannot afford that, so the connect runs in a
# daemon thread with a short timeout and a scheduler-driven retry.
_CONNECT_TIMEOUT_SECS = 3.0
_RETRY_DELAY_SECS     = 10.0
_pending: dict[str, Any] = {"awaiting_button_until": 0.0, "last_error": None}


# ── dependency import ──────────────────────────────────────────────
def _phue():
    try:
        import phue  # type: ignore
        return phue
    except Exception:
        return None


def is_available() -> bool:
    """Dep installed AND we have a bridge IP saved (or can autodiscover)."""
    if _phue() is None:
        return False
    cfg = _read_config()
    if cfg.get("bridge_ip"):
        return True
    # No saved bridge — still "available" if discovery is even possible,
    # but we don't probe the network here (latency); the first actual
    # call will exercise discovery.
    return True


# ── config ─────────────────────────────────────────────────────────
def _read_config() -> dict:
    if not os.path.exists(_CONFIG_PATH):
        return {}
    try:
        with open(_CONFIG_PATH, "r", encoding="utf-8") as f:
            return json.load(f) or {}
    except Exception:
        return {}


def _write_config(cfg: dict) -> None:
    os.makedirs(_DATA_DIR, exist_ok=True)
    try:
        from core.atomic_io import _atomic_write_json
        _atomic_write_json(_CONFIG_PATH, cfg)
    except Exception as e:
        print(f"  [sh-hue] config write failed: {e}")


# ── bridge discovery / connect ─────────────────────────────────────
def _valid_bridge_host(ip: str) -> bool:
    """True when `ip` is a literal IP address (v4/v6) or a hostname that
    actually resolves.  Guards the config against a misheard voice arg
    (the live file was once poisoned with bridge_ip="test", which
    permanently disabled autodiscovery)."""
    try:
        ipaddress.ip_address(ip)
        return True
    except ValueError:
        pass
    try:
        socket.getaddrinfo(ip, 80)
        return True
    except Exception:
        return False


def _autodiscover_bridge_ip() -> str | None:
    """Ask meethue.com's discovery endpoint for the local bridge IP.
    Hue bridges register themselves with Philips, so the cloud knows the
    public IP of every bridge on the user's LAN (well, the WAN, but the
    response contains the LAN-side IP in `internalipaddress`)."""
    try:
        import requests  # type: ignore
    except Exception:
        return None
    try:
        r = requests.get("https://discovery.meethue.com/", timeout=4)
        r.raise_for_status()
        data = r.json()
    except Exception as e:
        print(f"  [sh-hue] meethue discovery failed: {e}")
        return None
    if isinstance(data, list) and data:
        ip = data[0].get("internalipaddress")
        return ip or None
    return None


def _threaded_connect(phue_mod: Any, bridge_ip: str,
                      timeout: float = _CONNECT_TIMEOUT_SECS) -> dict:
    """Open phue.Bridge() + connect() in a daemon thread.

    Returns {"bridge", "error", "timed_out"}.  The phue.Bridge ctor itself
    calls connect() and can block ~30 s waiting for the bridge button to
    be pressed, so we cap that wait here.  If the worker times out we leak
    it as a daemon thread; should it eventually succeed it will be
    discarded (a later call will re-construct), which is fine — the bridge
    object holds no expensive resources.
    """
    result: dict[str, Any] = {"bridge": None, "error": None, "timed_out": False}

    def _worker() -> None:
        try:
            b = phue_mod.Bridge(bridge_ip)
            # phue.Bridge() already calls connect() internally on recent
            # versions, but call it again for safety on older ones.
            try:
                b.connect()
            except Exception:
                pass
            result["bridge"] = b
        except Exception as e:  # PhueRegistrationException et al.
            result["error"] = e

    t = threading.Thread(target=_worker,
                         name="sh_hue-connect",
                         daemon=True)
    t.start()
    t.join(timeout)
    if t.is_alive():
        result["timed_out"] = True
    return result


def _schedule_retry() -> None:
    """Ask core.scheduler to call hue_retry_connect in ~10 s.

    Gracefully no-ops if the scheduler module isn't importable or hasn't
    been bootstrapped yet (e.g. during early boot or if APScheduler
    deps aren't installed).
    """
    try:
        from core import scheduler  # type: ignore
    except Exception:
        return
    try:
        scheduler.schedule_once(
            action="hue_retry_connect",
            run_at=time.time() + _RETRY_DELAY_SECS,
            job_id="sh_hue_retry_connect",
            replace_existing=True,
        )
    except Exception as e:
        print(f"  [sh-hue] could not schedule connect retry: {e}")


def _get_bridge() -> Any:
    """Return a connected phue.Bridge (or None on failure). Caches the
    instance for `_CACHE_TTL_SECS`.  Connect is wrapped in a thread with a
    short timeout so a missed bridge-button-press cannot stall the voice
    loop for 30 s."""
    phue = _phue()
    if phue is None:
        return None
    with _lock:
        cached = _bridge_cache["bridge"]
        if cached is not None and (time.monotonic() - _bridge_cache["fetched_at"]) < _CACHE_TTL_SECS:
            return cached
    cfg = _read_config()
    from_config = bool(cfg.get("bridge_ip"))
    bridge_ip = cfg.get("bridge_ip") or _autodiscover_bridge_ip()
    if not bridge_ip:
        print("  [sh-hue] no bridge IP and discovery failed; "
              "set data/sh_hue_config.json or push the bridge button.")
        _pending["last_error"] = "no bridge IP"
        return None
    if not cfg.get("bridge_ip"):
        cfg["bridge_ip"] = bridge_ip
        _write_config(cfg)

    res = _threaded_connect(phue, bridge_ip)
    if res["timed_out"]:
        # Treat as "user hasn't pressed the button yet" — surface the hint
        # via the voice action and queue a retry.
        _pending["awaiting_button_until"] = time.time() + _RETRY_DELAY_SECS + 5.0
        _pending["last_error"] = "connect timed out"
        print(f"  [sh-hue] bridge connect timed out after "
              f"{_CONNECT_TIMEOUT_SECS:.0f}s — press the bridge button.")
        _schedule_retry()
        return None
    if res["error"] is not None:
        print(f"  [sh-hue] bridge connect failed: {res['error']}")
        _pending["last_error"] = str(res["error"])
        # PhueRegistrationException also means "press the button" — same hint.
        if "PhueRegistrationException" in res["error"].__class__.__name__:
            _pending["awaiting_button_until"] = time.time() + _RETRY_DELAY_SECS + 5.0
            _schedule_retry()
            return None
        # SELF-HEAL (2026-07-21): a generic connect error against a
        # CONFIG-supplied address may mean the stored bridge_ip is poisoned
        # (the live file once held the misheard voice arg "test").  Re-run
        # discovery: a different answer replaces the stored value and we
        # retry once; no answer + a syntactically-garbage stored value drops
        # the key so the next call rediscovers.  A valid stored IP survives
        # a transient outage untouched, and the timeout / registration
        # branches above never reach here — those mean "press the button",
        # so the stored IP is likely good.
        healed = False
        if from_config:
            discovered = _autodiscover_bridge_ip()
            if discovered and discovered != bridge_ip:
                cfg["bridge_ip"] = discovered
                _write_config(cfg)
                res = _threaded_connect(phue, discovered)
                healed = res["bridge"] is not None
                if healed:
                    print(f"  [sh-hue] stored bridge IP {bridge_ip!r} failed; "
                          f"reconnected via discovered {discovered}.")
                else:
                    _pending["last_error"] = (
                        f"stored bridge_ip {bridge_ip!r} failed; discovered "
                        f"{discovered} not connecting yet")
            elif not discovered and not _valid_bridge_host(bridge_ip):
                cfg.pop("bridge_ip", None)
                _write_config(cfg)
                print(f"  [sh-hue] dropped invalid stored bridge_ip "
                      f"{bridge_ip!r}; will rediscover on the next call.")
        if not healed:
            return None

    bridge = res["bridge"]
    with _lock:
        _bridge_cache["bridge"]     = bridge
        _bridge_cache["fetched_at"] = time.monotonic()
    # Successful connect clears the awaiting-button hint.
    _pending["awaiting_button_until"] = 0.0
    _pending["last_error"] = None
    return bridge


def _awaiting_button() -> bool:
    return time.time() < float(_pending.get("awaiting_button_until") or 0.0)


def hue_retry_connect(_: str = "") -> str:
    """Scheduler-triggered retry after a connect timeout.  Also user-callable."""
    bridge = _get_bridge()
    if bridge is not None:
        return "Hue bridge connected, sir."
    if _awaiting_button():
        return ("Still waiting on the Hue bridge button, sir — "
                "I'll keep retrying.")
    return f"Hue bridge unreachable: {_pending.get('last_error') or 'unknown'}"


def _light_by_name(bridge: Any, name: str) -> Any:
    """Find the phue.Light object whose name matches `name` (case-insensitive)."""
    if not bridge or not name:
        return None
    try:
        lights = bridge.get_light_objects(mode="name")  # dict[name → Light]
    except Exception:
        return None
    if name in lights:
        return lights[name]
    low = name.lower()
    for k, v in lights.items():
        if k.lower() == low:
            return v
    return None


# ── color conversion ──────────────────────────────────────────────
def _rgb_to_xy(rgb: tuple[int, int, int]) -> tuple[float, float]:
    """CIE 1931 xy chromaticity from sRGB. Approximation suitable for
    Hue bulbs; based on Philips' published gamma + matrix."""
    r, g, b = rgb
    rn, gn, bn = r / 255.0, g / 255.0, b / 255.0

    def _gamma(c: float) -> float:
        return ((c + 0.055) / 1.055) ** 2.4 if c > 0.04045 else c / 12.92

    rn, gn, bn = _gamma(rn), _gamma(gn), _gamma(bn)
    x = rn * 0.664511 + gn * 0.154324 + bn * 0.162028
    y = rn * 0.283881 + gn * 0.668433 + bn * 0.047685
    z = rn * 0.000088 + gn * 0.072310 + bn * 0.986039
    total = x + y + z
    if total <= 0:
        return (0.0, 0.0)
    return (x / total, y / total)


def _kelvin_to_mired(k: int) -> int:
    """Convert color temperature to mireds; Hue's ct range is 153..500."""
    if k <= 0:
        return 366  # default ~2700K
    mired = int(round(1_000_000 / k))
    return max(153, min(500, mired))


# ── public API ─────────────────────────────────────────────────────
def list_devices() -> list[dict]:
    """Return uniform device dicts for every bulb the bridge reports.
    Empty list on any error."""
    bridge = _get_bridge()
    if bridge is None:
        return []
    try:
        lights = bridge.get_light_objects(mode="name")
    except Exception as e:
        print(f"  [sh-hue] light enumeration failed: {e}")
        return []
    out: list[dict] = []
    for name, light in lights.items():
        caps = ["on_off"]
        try:
            if getattr(light, "colormode", None) in ("hs", "xy"):
                caps.append("color")
            if getattr(light, "colormode", None) == "ct":
                caps.append("color_temperature")
            caps.append("dim")
        except Exception:
            pass
        out.append({
            "name": name,
            "brand": "Philips Hue",
            "type":  "light",
            "capabilities": sorted(set(caps)),
            "native_id": getattr(light, "light_id", None),
        })
    return out


def get_state(device: dict) -> dict:
    bridge = _get_bridge()
    if bridge is None:
        return {"error": "hue bridge not connected"}
    light = _light_by_name(bridge, device.get("name", ""))
    if light is None:
        return {"error": f"bulb '{device.get('name')}' not found on bridge"}
    try:
        return {
            "on":         bool(getattr(light, "on", False)),
            "brightness": int(round((getattr(light, "brightness", 0) or 0) / 254 * 100)),
            "reachable":  bool(getattr(light, "reachable", True)),
        }
    except Exception as e:
        return {"error": f"hue state read failed: {e}"}


def set_state(device: dict, **kwargs) -> dict:
    """Apply the requested state changes to one Hue bulb.

    Accepted kwargs (a subset of these may be present per call):
        on:                bool
        brightness:        0..100  (percent → maps to phue 0..254)
        color:             (r, g, b) tuple
        color_temperature: kelvin (mapped to mireds)
    """
    bridge = _get_bridge()
    if bridge is None:
        return {"error": "hue bridge not connected"}
    light = _light_by_name(bridge, device.get("name", ""))
    if light is None:
        return {"error": f"bulb '{device.get('name')}' not found on bridge"}

    applied: dict[str, Any] = {}
    try:
        if "on" in kwargs and kwargs["on"] is not None:
            light.on = bool(kwargs["on"])
            applied["on"] = bool(kwargs["on"])
        if "brightness" in kwargs and kwargs["brightness"] is not None:
            pct = max(0, min(100, int(kwargs["brightness"])))
            light.brightness = int(round(pct / 100 * 254))
            applied["brightness"] = pct
            if pct > 0:
                light.on = True
                applied["on"] = True
        if "color" in kwargs and kwargs["color"]:
            xy = _rgb_to_xy(tuple(kwargs["color"]))
            try:
                light.xy = xy
                applied["color"] = list(xy)
            except Exception:
                # Bulb may be white-only; skip silently.
                pass
        if "color_temperature" in kwargs and kwargs["color_temperature"]:
            # Some Hue bulbs ('Color light' type, and certain older models)
            # lack a Kelvin range and only support hs/xy. Check the bulb's
            # type/colormode and skip silently rather than raise on those.
            ltype = (getattr(light, "type", "") or "").strip().lower()
            cmode = (getattr(light, "colormode", "") or "").strip().lower()
            ct_supported = True
            if ltype == "color light":
                ct_supported = False
            elif ltype in ("dimmable light", "on/off light"):
                ct_supported = False
            elif cmode == "hs" and ltype and "color" not in ltype:
                ct_supported = False
            if not ct_supported:
                applied["color_temperature_skipped"] = "bulb_lacks_ct_range"
            else:
                try:
                    light.colortemp = _kelvin_to_mired(int(kwargs["color_temperature"]))
                    applied["color_temperature_k"] = int(kwargs["color_temperature"])
                except Exception as _ct_err:
                    applied["color_temperature_skipped"] = f"unsupported: {_ct_err}"
    except Exception as e:
        return {"error": f"hue set_state failed mid-way: {e}",
                "partial": applied}

    return {"ok": True, "applied": applied}


# ── user-facing actions ─────────────────────────────────────────────
def hue_list(_: str = "") -> str:
    devs = list_devices()
    if not devs:
        if _awaiting_button():
            return ("Sir, press the button on your Hue bridge — "
                    f"I'll retry in {int(_RETRY_DELAY_SECS)} seconds.")
        return ("No Hue bulbs found, sir — bridge may not be reachable. "
                "Set data/sh_hue_config.json bridge_ip if needed.")
    names = [d["name"] for d in devs]
    return f"{len(names)} Hue bulb(s), sir: " + ", ".join(names[:10]) + (
        " (+more)" if len(names) > 10 else ""
    )


def hue_set_bridge_ip(arg: str = "") -> str:
    ip = (arg or "").strip()
    if not ip:
        return "Format: hue_set_bridge_ip, <ip>"
    if not _valid_bridge_host(ip):
        return (f"'{ip}' doesn't look like a bridge IP or resolvable host, "
                f"sir — not saved.")
    cfg = _read_config()
    cfg["bridge_ip"] = ip
    _write_config(cfg)
    with _lock:
        _bridge_cache["bridge"]     = None
        _bridge_cache["fetched_at"] = 0.0
    return f"Hue bridge IP set to {ip}, sir."


def register(actions: dict) -> None:
    actions["hue_list_devices"]    = hue_list
    actions["hue_list"]            = hue_list
    actions["hue_set_bridge_ip"]   = hue_set_bridge_ip
    actions["hue_retry_connect"]   = hue_retry_connect
